openapi: 3.0.0

info:
  title: SctInst API
  version: "1"

servers:
  - url: 'https://niania.requestcatcher.com'
    description: Dev server

paths:
  /test:
    get:
      parameters:
        - in: header
          name: Accept
          schema:
            type: string
        - in: header
          name: Accept-Encoding
          schema:
            type: string
        - in: header
          name: Connection
          schema:
            type: string
        - in: header
          name: Content-Length
          schema:
            type: string
        - in: header
          name: Content-Type
          schema:
            type: string
        - in: header
          name: Postman-Token
          schema:
            type: string
        - in: header
          name: User-Agent
          schema:
            type: string
        - in: header
          name: X-Username
          schema:
            type: string
        - in: header
          name: Host
          schema:
            type: string
      operationId: getTest
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TestResponse'

components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-username
  schemas:
    TestResponse:
      type: object
      properties:
        id:
          type: integer
        description:
          type: string
